name: Next.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Build Next.js Project
        run: npm run build

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_USER: ec2-user
          SERVER_IP: ${{ secrets.EC2_SERVER_IP }}
          TARGET: /var/www/lflabs

      - name: Install dependencies and restart server on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_SERVER_IP }} "
            cd /var/www/lflabs &&
            npm install &&
            npm run build &&
            pm2 restart next-app || pm2 start npm --name next-app -- run start:prod
          "
