name: Deploy to EC2

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Setup Private Key
      env:
        PRIVATE_KEY: ${{ secrets.EC2_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy Code to EC2 and Run Script
      env:
        EC2_INSTANCE_HOST: ${{ secrets.EC2_HOST }}
        EC2_INSTANCE_USER: ${{ secrets.EC2_USERNAME }}
        SITE_PATH: /home/${{ secrets.EC2_USERNAME }}/
      run: |
        ssh $EC2_INSTANCE_USER@$EC2_INSTANCE_HOST "rm -rf ${SITE_PATH}LF-Labs/"
        scp -r "${PWD}/" $EC2_INSTANCE_USER@$EC2_INSTANCE_HOST:$SITE_PATH
        ssh $EC2_INSTANCE_USER@$EC2_INSTANCE_HOST "cd ${SITE_PATH}LF-Labs && chmod +x deploy.sh && ./deploy.sh"
